chore!: update from module template
mineiros-io/terraform-google-secret-manager-iam pull request #17
Opened 2022-11-17 12:26 UTC by waxb

2022-11-17 12:33 UTC, mariux commented on README.tfdoc.hcl
> +          description = "The role that should be applied. Note that custom roles must be of the format `[projects|organizations]/{parent-name}/roles/{role-name}`. Must be set if `policy_binding` is u
please make it multi line string for better readability..

2022-11-17 12:35 UTC, mariux requested changes

2022-11-17 12:35 UTC, mariux commented on README.tfdoc.hcl
> +          description    = "A list of IAM policy bindings. Must be set if `role` is unset"
```suggestion
          description    = "A list of IAM policy bindings. If set `role` is ignored and a policy_binding is created."
```

2022-11-17 12:35 UTC, mariux commented on README.tfdoc.hcl
> +          description = "The role that should be applied. Note that custom roles must be of the format `[projects|organizations]/{parent-name}/roles/{role-name}`. Must be set if `policy_binding` is u
it's `policy_bindings`

2022-11-17 12:39 UTC, zied-elouaer requested changes

2022-11-17 12:39 UTC, zied-elouaer commented on README.tfdoc.hcl
> +          description    = "A list of IAM policy bindings. If set `role` is ignored and a policy_binding is created."
```suggestion
          description    = "A list of IAM policy bindings. If set, `role` is ignored and a policy_binding is created."
```

2022-11-17 12:55 UTC, zied-elouaer approved these changes
LGTM

2022-11-18 13:02 UTC, mariux approved these changes
lgtm

2022-11-18 14:24 UTC, merged